# Generated by Django 4.2.7 on 2025-09-30 20:44

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(blank=True, default='category.jpg', max_length=500, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('course_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(default=dict, help_text='SEO metadata and additional category info')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'api_category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=100, null=True)),
                ('platform_status', models.CharField(blank=True, choices=[('Review', 'Review'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Published', 'Published')], db_index=True, default='Published', max_length=100, null=True)),
                ('teacher_course_status', models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Published', 'Published')], db_index=True, default='Published', max_length=100)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('course_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', db_index=True, length=6, max_length=20, prefix='', unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('student_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('lecture_count', models.PositiveIntegerField(default=0)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('course_metadata', models.JSONField(default=dict, help_text='Additional course settings and metadata')),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('what_you_learn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_index=True, default=list, size=None)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
            options={
                'db_table': 'api_course',
            },
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('enrollment_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_study_time', models.DurationField(default=datetime.timedelta)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=1000)),
                ('qa_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(default=30)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('passing_score', models.PositiveIntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('variant_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', db_index=True, length=6, max_length=20, prefix='', unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.course')),
            ],
            options={
                'db_table': 'api_variant',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.URLField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, db_index=True, null=True)),
                ('preview', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('content_metadata', models.JSONField(default=dict, help_text='Additional content metadata')),
                ('variant_item_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', db_index=True, length=6, max_length=20, prefix='', unique=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='api.variant')),
            ],
            options={
                'db_table': 'api_variant_item',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('current_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_position', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variantitem')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.URLField(blank=True, default='default-user.jpg', max_length=500, null=True)),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('social_links', models.JSONField(default=dict, help_text='Store social media links as JSON')),
                ('about', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('total_students', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_courses', models.PositiveIntegerField(db_index=True, default=0)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_teacher',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=1)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_helpful', models.BooleanField(default=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='api.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='multiple_choice', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('choice_text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.quizquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.CreateModel(
            name='Question_Answer_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('message', models.TextField()),
                ('qam_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.question_answer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=1000)),
                ('note', models.TextField()),
                ('note_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=20, prefix='', unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enrolledcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher'),
        ),
        migrations.CreateModel(
            name='CompletedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variantitem')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('certificate_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('expires_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrolledcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['active', 'course_count'], name='api_categor_active_ae35db_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='api_categor_slug_794f78_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_categor_search__de5517_gin'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', '-created_at'], name='api_wishlis_user_id_cd5069_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'course'], name='api_videopr_user_id_6d3e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['variant_item', '-updated_at'], name='api_videopr_variant_4148aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('course', 'user', 'variant_item')},
        ),
        migrations.AddIndex(
            model_name='variantitem',
            index=models.Index(fields=['variant', 'order'], name='api_variant_variant_bf9e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='variantitem',
            index=models.Index(fields=['file_type', 'preview'], name='api_variant_file_ty_f13bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='variantitem',
            index=models.Index(fields=['variant_item_id'], name='api_variant_variant_06f4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['course', 'order'], name='api_variant_course__273dff_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['variant_id'], name='api_variant_variant_67a352_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['user', 'created_at'], name='api_teacher_user_id_a852c5_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['country', 'average_rating'], name='api_teacher_country_da77af_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_teacher_search__811d9c_gin'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['total_students', 'total_courses'], name='api_teacher_total_s_e86d77_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', '-rating', '-created_at'], name='api_review_course__c07d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='api_review_user_id_3c2688_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='api_quizque_quiz_id_a781a6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoice',
            index=models.Index(fields=['question', 'order'], name='api_quizcho_questio_774f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', '-started_at'], name='api_quizatt_user_id_72d923_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-score'], name='api_quizatt_quiz_id_6a0ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'is_active'], name='api_quiz_course__09956c_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['teacher', '-created_at'], name='api_quiz_teacher_3b8869_idx'),
        ),
        migrations.AddIndex(
            model_name='question_answer_message',
            index=models.Index(fields=['question', 'created_at'], name='api_questio_questio_a7da90_idx'),
        ),
        migrations.AddIndex(
            model_name='question_answer',
            index=models.Index(fields=['course', '-last_activity'], name='api_questio_course__d7ae60_idx'),
        ),
        migrations.AddIndex(
            model_name='question_answer',
            index=models.Index(fields=['user', '-created_at'], name='api_questio_user_id_66f15a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='api_notific_user_id_4b7939_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['teacher', '-created_at'], name='api_notific_teacher_c227bb_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'course', '-created_at'], name='api_note_user_id_0f0f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolledcourse',
            index=models.Index(fields=['user', '-last_activity'], name='api_enrolle_user_id_5ae08d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolledcourse',
            index=models.Index(fields=['course', '-created_at'], name='api_enrolle_course__4d291b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolledcourse',
            index=models.Index(fields=['teacher', '-created_at'], name='api_enrolle_teacher_b16461_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['platform_status', 'featured', '-date'], name='api_course_platfor_7bfea6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'platform_status'], name='api_course_categor_4b5342_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'teacher_course_status'], name='api_course_teacher_4e1e85_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['student_count', 'average_rating'], name='api_course_student_b45a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price', 'discount_price'], name='api_course_price_17a5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'platform_status'], name='api_course_level_fa5fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_course_search__338630_gin'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='api_course_tags_215ceb_gin'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['featured', 'platform_status', '-average_rating'], name='api_course_feature_b8d530_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'level', 'platform_status'], name='api_course_categor_3c4609_idx'),
        ),
        migrations.AddIndex(
            model_name='completedlesson',
            index=models.Index(fields=['user', 'course'], name='api_complet_user_id_c6d8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='completedlesson',
            index=models.Index(fields=['course', '-created_at'], name='api_complet_course__097c6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='completedlesson',
            unique_together={('course', 'user', 'variant_item')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', '-issued_date'], name='api_certifi_user_id_47059b_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['course', '-issued_date'], name='api_certifi_course__2cd2f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('course', 'user')},
        ),
    ]
