# Generated by Django 4.2.7 on 2025-10-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_cartorder_cartorderitem_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='student',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order_item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItem',
        ),
    ]
