# Generated by Django 4.2.7 on 2025-10-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_image_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Skill or expertise area', max_length=100)),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Advanced', help_text='Proficiency level', max_length=50)),
                ('color_gradient', models.CharField(blank=True, help_text="CSS gradient for badge (e.g., 'rgba(102, 126, 234, 0.1)')", max_length=200, null=True)),
                ('text_color', models.CharField(blank=True, help_text="Text color for badge (e.g., '#667eea')", max_length=50, null=True)),
                ('border_color', models.CharField(blank=True, help_text="Border color for badge (e.g., 'rgba(102, 126, 234, 0.2)')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='api.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Expertise',
                'verbose_name_plural': 'Teacher Expertise',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Resource name', max_length=200)),
                ('file_type', models.CharField(help_text='File type (e.g., PDF, ZIP)', max_length=50)),
                ('file_size', models.CharField(help_text='File size (e.g., 2.3 MB)', max_length=50)),
                ('file_url', models.URLField(help_text='URL to download the resource', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.course')),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resources',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(help_text='Requirement description')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.course')),
            ],
            options={
                'verbose_name': 'Course Requirement',
                'verbose_name_plural': 'Course Requirements',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField(help_text='Learning outcome description')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='api.course')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-video')", max_length=100)),
                ('text', models.CharField(help_text='Feature description', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('highlight', models.BooleanField(default=False, help_text='Highlight this feature')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.course')),
            ],
            options={
                'verbose_name': 'Course Feature',
                'verbose_name_plural': 'Course Features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
