# Generated by Django 4.2.7 on 2025-10-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacherexpertise_courseresource_courserequirement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['order', 'date']},
        ),
        migrations.AlterModelOptions(
            name='variantitem',
            options={'ordering': ['order', 'date']},
        ),
        migrations.AddField(
            model_name='variant',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
