# Generated by Django 4.2.7 on 2025-10-18 10:07

from django.db import migrations
from django.utils.text import slugify


def fix_course_slugs(apps, schema_editor):
    """
    Fix course slugs that contain 'None' due to the previous bug where
    self.pk was None during slug generation.
    """
    Course = apps.get_model('api', 'Course')
    fixed_count = 0
    
    for course in Course.objects.all():
        if not course.slug or 'None' in course.slug or course.slug == '':
            # Generate new slug
            base_slug = slugify(course.title) if course.title else f'course-{course.pk}'
            new_slug = f"{base_slug}-{course.pk}"
            
            # Ensure uniqueness
            original_slug = new_slug
            counter = 1
            while Course.objects.filter(slug=new_slug).exclude(pk=course.pk).exists():
                new_slug = f"{original_slug}-{counter}"
                counter += 1
            
            course.slug = new_slug
            course.save(update_fields=['slug'])
            fixed_count += 1
            print(f"Fixed course {course.pk}: {course.title} -> slug: {new_slug}")
    
    print(f"\nTotal courses fixed: {fixed_count}")


def reverse_fix(apps, schema_editor):
    """
    Reverse migration - no action needed as we can't restore broken slugs
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fix_course_slugs_with_none'),
    ]

    operations = [
        migrations.RunPython(fix_course_slugs, reverse_fix),
    ]

