# Generated by Django 4.2.7 on 2025-11-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fix_existing_course_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(default='external_users', help_text='Type of sync operation (e.g., external_users, courses, etc.)', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the sync started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the sync completed', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='in_progress', help_text='Current status of the sync', max_length=20)),
                ('total_records', models.IntegerField(default=0, help_text='Total records processed')),
                ('created_records', models.IntegerField(default=0, help_text='New records created')),
                ('updated_records', models.IntegerField(default=0, help_text='Existing records updated')),
                ('failed_records', models.IntegerField(default=0, help_text='Records that failed to sync')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the sync', null=True)),
            ],
            options={
                'verbose_name': 'Sync History',
                'verbose_name_plural': 'Sync Histories',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='api_synchis_started_55cde3_idx'), models.Index(fields=['status', '-started_at'], name='api_synchis_status_dff6d7_idx')],
            },
        ),
    ]
