# Generated by Django 4.2.7 on 2025-11-11 07:55

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_synchistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='validation_token',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=12, max_length=20, prefix='', unique=True),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['validation_token'], name='api_certifi_validat_ed5942_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='api_certifi_certifi_d284a3_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'course'], name='api_certifi_user_id_9e4790_idx'),
        ),
    ]
