# Generated by Django 4.2.7 on 2025-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_certificate_validation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='platform_status',
            field=models.CharField(blank=True, choices=[('Review', 'Review'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Published', 'Published')], db_index=True, default='Draft', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_course_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Published', 'Published')], db_index=True, default='Draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
