# Generated by Django 4.2.7 on 2025-11-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_platform_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='platform_status',
            field=models.CharField(blank=True, choices=[('Review', 'Review'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_course_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Published', 'Published')], default='Draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Search Analytics',
                'ordering': ['-search_count', '-updated_at'],
                'indexes': [models.Index(fields=['-search_count'], name='api_searcha_search__a3166f_idx'), models.Index(fields=['-updated_at'], name='api_searcha_updated_2eb86e_idx')],
            },
        ),
    ]
