# Generated by Django 4.2.7 on 2025-11-22 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_coursesearchanalytics_searchlog_course_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0, help_text='Average score across attempts')),
                ('pass_rate', models.FloatField(default=0, help_text='% of attempts that passed (>=70%)')),
                ('discrimination_index', models.FloatField(default=0, help_text='0-1: ability to distinguish high/low performers')),
                ('difficulty_rating', models.CharField(choices=[('too_easy', 'Too Easy'), ('appropriate', 'Appropriate'), ('too_hard', 'Too Hard')], default='appropriate', max_length=20)),
                ('avg_time_minutes', models.FloatField(default=0, help_text='Average time to complete')),
                ('last_calibrated', models.DateTimeField(auto_now=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.quiz')),
            ],
            options={
                'ordering': ['quiz'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0, help_text='Risk score 0-100')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=10)),
                ('indicators', models.JSONField(default=dict, help_text='Risk factors: low_completion, quiz_failures, inactive_days, low_video_progress')),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('intervention_sent', models.BooleanField(default=False)),
                ('intervention_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='api.enrolledcourse')),
            ],
            options={
                'ordering': ['-risk_score'],
                'indexes': [models.Index(fields=['-risk_score'], name='api_student_risk_sc_2ae212_idx'), models.Index(fields=['risk_level'], name='api_student_risk_le_4041ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('intent_type', models.CharField(choices=[('skill_learning', 'Learning a Skill'), ('problem_solving', 'Solving a Problem'), ('career_change', 'Career Change'), ('general', 'General Interest')], default='general', max_length=50)),
                ('related_keywords', models.JSONField(default=list, help_text='Keywords associated with this intent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_courses', models.ManyToManyField(blank=True, help_text='Courses matching this intent', related_name='search_intents', to='api.course')),
            ],
            options={
                'ordering': ['query'],
                'indexes': [models.Index(fields=['intent_type'], name='api_searchi_intent__ff9aec_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Path title (e.g., 'Python Master')", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty_progression', models.CharField(choices=[('beginner', 'Beginner → Intermediate → Advanced'), ('mixed', 'Mixed Difficulty'), ('advanced', 'Advanced Only')], default='beginner', max_length=50)),
                ('estimated_duration_hours', models.IntegerField(help_text='Total estimated hours to complete')),
                ('completion_percentage', models.FloatField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('courses_total', models.IntegerField(default=1)),
                ('effectiveness_score', models.FloatField(default=0, help_text='0-100 how well path matches student')),
                ('success_probability', models.FloatField(default=0, help_text='Estimated % chance to complete all')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_learnin_user_id_be18f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstructorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.FloatField(default=0, help_text='Average course rating 1-5')),
                ('total_ratings', models.IntegerField(default=0)),
                ('course_count', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('avg_completion_rate', models.FloatField(default=0, help_text='Average completion % across courses')),
                ('avg_qa_response_time_hours', models.FloatField(default=0, help_text='Hours to respond to Q&A')),
                ('qa_response_rate', models.FloatField(default=0, help_text='% of questions answered')),
                ('positive_reviews_pct', models.FloatField(default=0, help_text='% of positive reviews')),
                ('teaching_effectiveness_score', models.FloatField(default=0, help_text='0-100 composite score')),
                ('period_start', models.DateField(auto_now_add=True)),
                ('period_end', models.DateField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='api.teacher')),
            ],
            options={
                'ordering': ['-teaching_effectiveness_score'],
                'indexes': [models.Index(fields=['-teaching_effectiveness_score'], name='api_instruc_teachin_f4bd70_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Recommendation score 0-100')),
                ('reason', models.CharField(choices=[('similar_search', 'Similar to your search'), ('similar_course', 'Similar to completed course'), ('trending_category', 'Trending in your category'), ('collaborative', 'Users like you enrolled'), ('skill_progression', 'Next skill to learn')], max_length=50)),
                ('clicked', models.BooleanField(default=False)),
                ('enrolled', models.BooleanField(default=False)),
                ('click_date', models.DateTimeField(blank=True, null=True)),
                ('enroll_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to_users', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', '-score'], name='api_courser_user_id_9acba1_idx'), models.Index(fields=['reason'], name='api_courser_reason_9dbdcb_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ContentGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('attempt_count', models.IntegerField(default=1, help_text='Number of times searched')),
                ('unique_users', models.IntegerField(default=1, help_text='Number of unique users searching')),
                ('priority_score', models.FloatField(default=0, help_text='Calculated priority (0-100)')),
                ('suggested_course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_category', models.ForeignKey(blank=True, help_text='Suggested category for the course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
            options={
                'ordering': ['-priority_score', '-attempt_count'],
                'indexes': [models.Index(fields=['-priority_score'], name='api_content_priorit_d14899_idx'), models.Index(fields=['-attempt_count'], name='api_content_attempt_c73421_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_probability', models.FloatField(help_text='0-100 probability of churn')),
                ('risk_signals', models.JSONField(default=dict, help_text='Individual risk factors: days_inactive, courses_in_progress, quiz_failures, negative_reviews, engagement_trend')),
                ('intervention_status', models.CharField(choices=[('none', 'No Intervention'), ('email_sent', 'Email Sent'), ('message_sent', 'Message Sent'), ('mentor_assigned', 'Mentor Assigned'), ('re_engaged', 'Re-engaged')], default='none', max_length=50)),
                ('intervention_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='churn_prediction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-churn_probability'],
                'indexes': [models.Index(fields=['-churn_probability'], name='api_churnpr_churn_p_4fa479_idx')],
            },
        ),
    ]
