# Generated by Django 4.2.7 on 2025-11-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_quizmetrics_studentriskassessment_searchintent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('SKILL', 'Technical Skill'), ('COURSE_TYPE', 'Course Type'), ('LEVEL', 'Proficiency Level'), ('TOPIC', 'Subject Topic'), ('TOOL', 'Tool/Framework'), ('DOMAIN', 'Business Domain'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('query_patterns', models.JSONField(default=list, help_text='List of keywords or regex patterns that match this category')),
                ('description', models.TextField(blank=True, null=True)),
                ('trending', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTaxonomyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_searches', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_failures', models.IntegerField(default=0)),
                ('unique_queries', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('avg_ctr', models.FloatField(default=0.0)),
                ('failed_rate', models.FloatField(default=0.0)),
                ('trending_score', models.FloatField(default=0.0, help_text='0-100 trending indicator')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.searchquerycategory')),
            ],
            options={
                'verbose_name_plural': 'Search Taxonomy Analytics',
            },
        ),
        migrations.CreateModel(
            name='SearchQueryTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(db_index=True, max_length=255)),
                ('search_count', models.IntegerField(default=1, help_text='Total times this query was searched')),
                ('click_through_count', models.IntegerField(default=0, help_text='Times a result was clicked')),
                ('failed_count', models.IntegerField(default=0, help_text='Times it returned 0 results')),
                ('unique_users', models.IntegerField(default=1, help_text='Unique users who searched this')),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='api.searchquerycategory')),
            ],
            options={
                'verbose_name_plural': 'Search Query Taxonomies',
            },
        ),
        migrations.AddIndex(
            model_name='searchquerycategory',
            index=models.Index(fields=['category_type', 'trending'], name='api_searchq_categor_b11c1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchquerycategory',
            unique_together={('category_type', 'category_name')},
        ),
        migrations.AddIndex(
            model_name='searchquerytaxonomy',
            index=models.Index(fields=['category', 'search_count'], name='api_searchq_categor_3cbc10_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerytaxonomy',
            index=models.Index(fields=['created_at'], name='api_searchq_created_86dc67_idx'),
        ),
    ]
