# Generated by Django 4.2.7 on 2025-12-04 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notification_message_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='api.course'),
        ),
    ]
