# Generated by Django 4.2.7 on 2026-02-15 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_add_review_role_field"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_user_course_role_review",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="api_review_role_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="api_review_user_role_idx",
        ),
    ]
