# Generated by Django 4.2.7 on 2026-02-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_course_approval_workflow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variant",
            options={
                "ordering": ["order", "date"],
                "verbose_name": "Bagian",
                "verbose_name_plural": "Bagian-Bagian",
            },
        ),
        migrations.AlterModelOptions(
            name="variantitem",
            options={
                "ordering": ["order", "date"],
                "verbose_name": "Pelajaran",
                "verbose_name_plural": "Pelajaran-Pelajaran",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="platform_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Review", "Review"),
                    ("Disabled", "Disabled"),
                    ("Rejected", "Rejected"),
                    ("Draft", "Draft"),
                    ("Published", "Published"),
                ],
                default="Draft",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="review_submitted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
