# Generated by Django 4.2.8 on 2026-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_alter_variant_options_alter_variantitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="intro_video_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upload", "Upload File"),
                    ("youtube", "YouTube Link"),
                    ("google_drive", "Google Drive"),
                ],
                default="upload",
                max_length=20,
                null=True,
            ),
        ),
    ]
