# Generated by Django 4.2.7 on 2026-02-20 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_course_versioning_phase_4_60"),
        ("api", "0038_alter_course_intro_video_source"),
    ]

    operations = []
