# Generated by Django 4.2.8 on 2026-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_merge_20260220_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="published_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="JSON snapshot of course state when published (for restore functionality)",
                null=True,
            ),
        ),
    ]
