# Generated by Django 4.2.8 on 2026-02-22 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0040_course_published_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expertise_areas",
                    models.CharField(
                        help_text="Bidang keahlian yang ingin diajarkan (pisahkan dengan koma)",
                        max_length=500,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Pengenalan singkat tentang Anda dan pengalaman mengajar"
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Pemula (0-2 tahun)"),
                            ("INTERMEDIATE", "Menengah (2-5 tahun)"),
                            ("ADVANCED", "Lanjutan (5+ tahun)"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu Review Admin"),
                            ("APPROVED", "Disetujui"),
                            ("REJECTED", "Ditolak"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Alasan penolakan (jika status=REJECTED)",
                        null=True,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructor_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructor Request",
                "verbose_name_plural": "Instructor Requests",
                "ordering": ["-request_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="api_instruc_user_id_d54834_idx"
                    ),
                    models.Index(
                        fields=["status", "-request_date"],
                        name="api_instruc_status_8a91f6_idx",
                    ),
                    models.Index(
                        fields=["reviewed_date"], name="api_instruc_reviewe_ff6889_idx"
                    ),
                ],
            },
        ),
    ]
