# Generated by Django 4.2.7 on 2026-02-25 10:14

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_instructorrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCompletionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question that will be displayed to the student"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice (Single Select)"),
                            ("multi_select", "Multi-Select"),
                            ("short_answer", "Short Answer"),
                            ("fill_in_blank", "Fill in the Blank"),
                        ],
                        default="multiple_choice",
                        help_text="Type of question: multiple choice, multi-select, short answer, or fill in blank",
                        max_length=20,
                    ),
                ),
                (
                    "correct_answer_text",
                    models.TextField(
                        blank=True,
                        help_text="For short answer/fill in blank: the correct answer text",
                        null=True,
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="For short answer/fill in blank: whether answer is case-sensitive",
                    ),
                ),
                (
                    "question_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=6,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_question",
                        to="api.variantitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Completion Question",
                "verbose_name_plural": "Lesson Completion Questions",
            },
        ),
        migrations.CreateModel(
            name="LessonCompletionQuestionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "choice_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=6,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        limit_choices_to={
                            "question_type__in": ["multiple_choice", "multi_select"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="api.lessoncompletionquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Completion Question Choice",
                "verbose_name_plural": "Lesson Completion Question Choices",
                "ordering": ["order"],
            },
        ),
    ]
