# Generated by Django 4.2.8 on 2026-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_lessoncompletionquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantitem",
            name="media_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upload", "Upload File"),
                    ("youtube", "YouTube Link"),
                    ("google_drive", "Google Drive"),
                ],
                default="google_drive",
                max_length=20,
                null=True,
            ),
        ),
    ]
