# Generated by Django 4.2.8 on 2026-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0099_reviewabuse"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewabuse",
            name="closed_by_reporter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewabuse",
            name="closed_by_reporter_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
