# Generated by Django 4.2.8 on 2026-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0100_reviewabuse_closed_by_reporter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
