# Generated by Django 4.2.8 on 2026-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0101_certificate_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="image_file",
            field=models.FileField(
                blank=True, null=True, upload_to="certificates/images/"
            ),
        ),
    ]
