# Generated by Django 4.2.8 on 2026-02-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_certificate_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='variant_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='api.variantitem'),
        ),
    ]
