# Generated by Django 4.2.8 on 2026-03-01 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0104_question_answer_report_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question_answer_message_report",
            options={"ordering": ["-reported_at"]},
        ),
        migrations.AlterModelOptions(
            name="question_answer_report",
            options={"ordering": ["-reported_at"]},
        ),
        migrations.RemoveField(
            model_name="question_answer_message_report",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="question_answer_report",
            name="created_at",
        ),
        migrations.AddField(
            model_name="question_answer_message_report",
            name="reported_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question_answer_message_report",
            name="review_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question_answer_message_report",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question_answer_message_report",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qa_message_report_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question_answer_report",
            name="reported_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question_answer_report",
            name="review_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question_answer_report",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question_answer_report",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qa_report_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question_answer_message_report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("reviewed", "Reviewed"),
                    ("dismissed", "Dismissed"),
                    ("action_taken", "Action Taken"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question_answer_report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("reviewed", "Reviewed"),
                    ("dismissed", "Dismissed"),
                    ("action_taken", "Action Taken"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
