# Generated by Django 4.2.8 on 2026-03-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0105_alter_question_answer_message_report_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question_answer_message",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="api.question_answer",
            ),
        ),
    ]
