# Generated by Django 4.2.8 on 2026-03-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0107_alter_question_answer_message_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="api.variant",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="variant_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="api.variantitem",
            ),
        ),
    ]
