# Generated by Django 4.2.8 on 2026-03-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0108_note_variant_note_variant_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lifetime_points", models.IntegerField(db_index=True, default=0)),
                ("lifetime_updated", models.DateTimeField(auto_now=True)),
                ("yearly_points", models.IntegerField(default=0)),
                (
                    "yearly_year",
                    models.IntegerField(default=0, help_text="Year for yearly ranking"),
                ),
                ("yearly_updated", models.DateTimeField(auto_now=True)),
                ("monthly_points", models.IntegerField(default=0)),
                (
                    "monthly_year",
                    models.IntegerField(
                        default=0, help_text="Year for monthly ranking"
                    ),
                ),
                (
                    "monthly_month",
                    models.IntegerField(
                        default=0, help_text="Month (1-12) for monthly ranking"
                    ),
                ),
                ("monthly_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Points",
                "verbose_name_plural": "Student Points",
                "ordering": ["-lifetime_points"],
                "indexes": [
                    models.Index(
                        fields=["-lifetime_points"],
                        name="api_student_lifetim_2dc9ff_idx",
                    ),
                    models.Index(
                        fields=["-yearly_points"], name="api_student_yearly__22aaf2_idx"
                    ),
                    models.Index(
                        fields=["-monthly_points"],
                        name="api_student_monthly_1d22d2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InstructorPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lifetime_points", models.IntegerField(db_index=True, default=0)),
                ("lifetime_updated", models.DateTimeField(auto_now=True)),
                ("yearly_points", models.IntegerField(default=0)),
                (
                    "yearly_year",
                    models.IntegerField(default=0, help_text="Year for yearly ranking"),
                ),
                ("yearly_updated", models.DateTimeField(auto_now=True)),
                ("monthly_points", models.IntegerField(default=0)),
                (
                    "monthly_year",
                    models.IntegerField(
                        default=0, help_text="Year for monthly ranking"
                    ),
                ),
                (
                    "monthly_month",
                    models.IntegerField(
                        default=0, help_text="Month (1-12) for monthly ranking"
                    ),
                ),
                ("monthly_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="api.teacher",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructor Points",
                "verbose_name_plural": "Instructor Points",
                "ordering": ["-lifetime_points"],
                "indexes": [
                    models.Index(
                        fields=["-lifetime_points"],
                        name="api_instruc_lifetim_3edb0a_idx",
                    ),
                    models.Index(
                        fields=["-yearly_points"], name="api_instruc_yearly__b73d2d_idx"
                    ),
                    models.Index(
                        fields=["-monthly_points"],
                        name="api_instruc_monthly_6c9228_idx",
                    ),
                ],
            },
        ),
    ]
