# Generated by Django 4.2.8 on 2026-03-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0109_add_ranking_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_type",
                    models.CharField(
                        choices=[
                            ("student", "Student Points"),
                            ("instructor", "Instructor Points"),
                        ],
                        help_text="Whether this is StudentPoints or InstructorPoints",
                        max_length=20,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("course_completion", "Course Completion"),
                            ("quiz_score", "Quiz Score"),
                            ("rating_given", "Rating Given by Student"),
                            ("student_rating", "Rating Received by Instructor"),
                            ("course_published", "Course Published"),
                            ("student_enrollment", "Student Enrollment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("points_awarded", models.IntegerField()),
                (
                    "course_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Course ID if related to course activity",
                        null=True,
                    ),
                ),
                (
                    "quiz_id",
                    models.IntegerField(
                        blank=True, help_text="Quiz ID if related to quiz", null=True
                    ),
                ),
                (
                    "review_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Review ID if related to review",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Human readable explanation of what earned these points",
                        max_length=500,
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_audit_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Points Audit Log",
                "verbose_name_plural": "Points Audit Logs",
                "ordering": ["-awarded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-awarded_at"],
                        name="api_pointsa_user_id_f3b453_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-awarded_at"],
                        name="api_pointsa_activit_c05845_idx",
                    ),
                    models.Index(
                        fields=["points_type", "-awarded_at"],
                        name="api_pointsa_points__544663_idx",
                    ),
                ],
            },
        ),
    ]
