# Generated by Django 4.2.8 on 2026-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0110_pointsauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="_points_awarded",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Points awarded for this attempt",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="_points_awarded",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Points awarded for this review",
            ),
        ),
    ]
