# Generated by Django 4.2.8 on 2026-03-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0111_quizattempt__points_awarded_review__points_awarded"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("bug", "Bug Report"), ("feature", "Feature Request")],
                        default="bug",
                        help_text="Type of feedback: bug report or feature request",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the issue or request", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the bug or feature"
                    ),
                ),
                (
                    "related_url",
                    models.URLField(
                        blank=True,
                        help_text="URL where the issue occurred or feature is needed",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "affected_area",
                    models.CharField(
                        blank=True,
                        help_text="Component/area affected (e.g., 'Search', 'Enrollment', 'Dashboard')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("wont_fix", "Won't Fix"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Current status of the feedback",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Priority level assigned by admin",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes and updates from admin/dev team",
                        null=True,
                    ),
                ),
                (
                    "attachments",
                    models.URLField(
                        blank=True,
                        help_text="URL to screenshot or supporting document",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when issue was resolved",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/developer assigned to handle this feedback",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related course if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="api.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feedback",
                "verbose_name_plural": "User Feedbacks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="api_feedbac_created_17f3f6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api_feedbac_status_693c36_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="api_feedbac_priorit_59d775_idx"
                    ),
                    models.Index(
                        fields=["feedback_type"], name="api_feedbac_feedbac_9d3a98_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="api_feedbac_user_id_2f606a_idx",
                    ),
                ],
            },
        ),
    ]
