# Generated by Django 4.2.8 on 2026-03-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0117_tag_course_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="api_feedbac_user_id_2f606a_idx",
        ),
        migrations.RenameIndex(
            model_name="activityaggregate",
            new_name="api_activit_date_60680b_idx",
            old_name="api_activi_date_period_idx",
        ),
        migrations.RenameIndex(
            model_name="activityaggregate",
            new_name="api_activit_user_id_b05550_idx",
            old_name="api_activi_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="activityaggregate",
            new_name="api_activit_course__1139fe_idx",
            old_name="api_activi_course_date_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="api_activit_user_id_d7cebe_idx",
            old_name="api_activi_user_id_act_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="api_activit_user_id_a7fb6f_idx",
            old_name="api_activi_user_id_act_type_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="api_activit_course__a84676_idx",
            old_name="api_activi_course_act_date_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="api_activit_activit_e34b5f_idx",
            old_name="api_activi_act_type_date_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="api_activit_activit_7a3899_idx",
            old_name="api_activi_act_date_idx",
        ),
        migrations.RemoveField(
            model_name="course",
            name="intro_video_source",
        ),
        migrations.RemoveField(
            model_name="review",
            name="_points_awarded",
        ),
        migrations.RemoveField(
            model_name="variantitem",
            name="media_source",
        ),
        migrations.AlterField(
            model_name="activityaggregate",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("enrollment", "Pendaftaran Kursus"),
                    ("lesson_started", "Mulai Pelajaran"),
                    ("lesson_completed", "Selesaikan Pelajaran"),
                    ("video_watched", "Tonton Video"),
                    ("video_completed", "Video Selesai (95%+)"),
                    ("quiz_attempted", "Kerjakan Kuis"),
                    ("quiz_passed", "Lulus Kuis"),
                    ("quiz_failed", "Tidak Lulus Kuis"),
                    ("certificate_earned", "Raih Sertifikat"),
                    ("course_completed", "Selesaikan Kursus"),
                    ("question_asked", "Buat Pertanyaan"),
                    ("question_answered", "Jawab Pertanyaan"),
                    ("review_posted", "Posting Review"),
                    ("points_earned", "Dapatkan Poin"),
                    ("search_query", "Cari Kursus"),
                    ("content_liked", "Sukai Konten"),
                    ("wishlist_added", "Tambah Wishlist"),
                    ("discussion_participated", "Ikut Diskusi"),
                    ("course_created", "Buat Kursus"),
                    ("course_updated", "Update Kursus"),
                    ("course_published", "Publikasikan Kursus"),
                    ("lesson_created", "Tambah Pelajaran"),
                    ("lesson_updated", "Update Pelajaran"),
                    ("quiz_created", "Buat Kuis"),
                    ("student_enrolled_manual", "Daftar Siswa Secara Manual"),
                    ("student_unenrolled", "Hapus Siswa"),
                    ("announcement_posted", "Posting Pengumuman"),
                    ("grade_recorded", "Berikan Nilai"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="activityfilter",
            name="activity_types",
            field=models.JSONField(
                default=list, help_text="List of activity types to display"
            ),
        ),
        migrations.AlterField(
            model_name="activityfilter",
            name="include_failed_activities",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activityfilter",
            name="include_system_activities",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="activityfilter",
            name="max_activities_display",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="activityfilter",
            name="sort_by",
            field=models.CharField(
                choices=[("date", "Terbaru"), ("engagement", "Paling Engaging")],
                default="date",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activityfilter",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_filter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("enrollment", "Pendaftaran Kursus"),
                    ("lesson_started", "Mulai Pelajaran"),
                    ("lesson_completed", "Selesaikan Pelajaran"),
                    ("video_watched", "Tonton Video"),
                    ("video_completed", "Video Selesai (95%+)"),
                    ("quiz_attempted", "Kerjakan Kuis"),
                    ("quiz_passed", "Lulus Kuis"),
                    ("quiz_failed", "Tidak Lulus Kuis"),
                    ("certificate_earned", "Raih Sertifikat"),
                    ("course_completed", "Selesaikan Kursus"),
                    ("question_asked", "Buat Pertanyaan"),
                    ("question_answered", "Jawab Pertanyaan"),
                    ("review_posted", "Posting Review"),
                    ("points_earned", "Dapatkan Poin"),
                    ("search_query", "Cari Kursus"),
                    ("content_liked", "Sukai Konten"),
                    ("wishlist_added", "Tambah Wishlist"),
                    ("discussion_participated", "Ikut Diskusi"),
                    ("course_created", "Buat Kursus"),
                    ("course_updated", "Update Kursus"),
                    ("course_published", "Publikasikan Kursus"),
                    ("lesson_created", "Tambah Pelajaran"),
                    ("lesson_updated", "Update Pelajaran"),
                    ("quiz_created", "Buat Kuis"),
                    ("student_enrolled_manual", "Daftar Siswa Secara Manual"),
                    ("student_unenrolled", "Hapus Siswa"),
                    ("announcement_posted", "Posting Pengumuman"),
                    ("grade_recorded", "Berikan Nilai"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes from admins", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="affected_area",
            field=models.CharField(
                choices=[
                    ("course", "Kursus"),
                    ("video", "Video"),
                    ("quiz", "Kuis"),
                    ("forum", "Forum"),
                    ("ui", "Antarmuka Pengguna"),
                    ("account", "Akun"),
                    ("other", "Lainnya"),
                ],
                db_index=True,
                default="other",
                help_text="Component or area affected",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin assigned to handle this feedback",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="attachments",
            field=models.URLField(
                blank=True, help_text="Screenshot or document URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the issue or feature request",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[("bug", "Bug Report"), ("feature", "Feature Request")],
                db_index=True,
                help_text="Type of feedback: bug report or feature request",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Rendah"),
                    ("medium", "Sedang"),
                    ("high", "Tinggi"),
                    ("critical", "Kritis"),
                ],
                db_index=True,
                default="medium",
                help_text="Priority level for resolution",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="related_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Related course if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_items",
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="related_url",
            field=models.URLField(
                blank=True, help_text="URL where the issue occurred", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Terbuka"),
                    ("under_review", "Dalam Tinjauan"),
                    ("in_progress", "Sedang Dikerjakan"),
                    ("resolved", "Diselesaikan"),
                    ("wont_fix", "Tidak Akan Diperbaiki"),
                    ("closed", "Ditutup"),
                ],
                db_index=True,
                default="open",
                help_text="Current status of the feedback",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(
                help_text="Brief summary of the feedback", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="lessoncompletionquestionanswer",
            name="answer_choice",
            field=models.ForeignKey(
                blank=True,
                help_text="For single-select questions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.lessoncompletionquestionchoice",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncompletionquestionanswer",
            name="answer_choices",
            field=models.ManyToManyField(
                blank=True,
                help_text="For multi-select questions",
                related_name="student_multi_select_answers",
                to="api.lessoncompletionquestionchoice",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncompletionquestionanswer",
            name="answer_text",
            field=models.TextField(
                blank=True, help_text="For text-based answers", null=True
            ),
        ),
        migrations.AlterField(
            model_name="lessoncompletionquestionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_answers",
                to="api.lessoncompletionquestion",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncompletionquestionanswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_completion_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Course section (bagian) this note relates to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.variant",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="variant_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Lesson (pelajaran) this note relates to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.variantitem",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["user"], name="api_feedbac_user_id_5cf24a_idx"),
        ),
        migrations.AddIndex(
            model_name="lessoncompletionquestionanswer",
            index=models.Index(
                fields=["user", "question", "-answered_at"],
                name="api_lessonc_user_id_eb6c48_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="feedback",
            table="api_feedback",
        ),
        migrations.AlterModelTable(
            name="pointsauditlog",
            table="api_pointsauditlog",
        ),
    ]
