# Generated by Django 4.2.8 on 2026-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0118_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="user_role_at_submission",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                ],
                default="student",
                editable=False,
                help_text="User role captured at the time feedback was submitted (immutable)",
                max_length=20,
            ),
        ),
    ]
