# Generated by Django 4.2.8 on 2026-09-22 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0119_add_user_role_at_submission_to_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz1234567890",
                        help_text="Public identifier for file operations",
                        length=12,
                        max_length=25,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Nama asli file dari klien", max_length=255
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path relatif penyimpanan di storage (misal: course-file/uuid.png)",
                        max_length=500,
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        db_index=True, help_text="URL publik file", max_length=1000
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Ukuran file dalam bytes"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        default="other",
                        help_text="Kategori file (image, video, document, other)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User yang mengunggah file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_uploadedfile",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["uploaded_by", "-created_at"],
                        name="api_uploade_uploade_24edb2_idx",
                    ),
                    models.Index(
                        fields=["file_url"], name="api_uploade_file_ur_88fd9c_idx"
                    ),
                    models.Index(
                        fields=["file_id"], name="api_uploade_file_id_e60870_idx"
                    ),
                ],
            },
        ),
    ]
