import os
import sys
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from api.models import Course, Teacher
from userauths.models import User
import uuid

print("=" * 70)
print("RECREATING DELETED COURSES")
print("=" * 70)
print()

# Get user first (admin)
try:
    user = User.objects.get(id=1)
    print(f"✅ Found user: {user.username} (ID: {user.id})")
except Exception as e:
    print(f"❌ User with ID 1 not found: {e}")
    sys.exit(1)

# Get or create teacher for this user
try:
    teacher = Teacher.objects.get(user=user)
    print(f"✅ Found teacher: {teacher.user.username}")
except:
    print("⚠️  Creating teacher profile for user...")
    teacher = Teacher.objects.create(user=user)
    print(f"✅ Created teacher: {teacher.user.username}")

# Recreate the course
# DON'T specify course_id - let ShortUUIDField auto-generate it
course = Course.objects.create(
    # course_id will be auto-generated by ShortUUIDField
    title="Public Speaking Course",
    description="A course on public speaking.",
    slug="public-speaking",  # Shortened slug to fit character limit
    teacher=teacher,
    platform_status="Published",
    teacher_course_status="Published",
)

print(f"✅ Course recreated!")
print(f"   Course ID: {course.course_id}")
print(f"   DB ID: {course.id}")
print(f"   Title: {course.title[:60]}")
print(f"   Status: {course.platform_status} / {course.teacher_course_status}")
print()

# Verify
published_count = Course.objects.filter(
    platform_status="Published",
    teacher_course_status="Published"
).count()

print(f"📊 Published courses in database NOW: {published_count}")
print()
print("=" * 70)
print("✅ Database fixed - course restored!")
print("=" * 70)
