"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from environs import Env
env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-+c@7t#q96f*r#f-@ss1$2r5a3!xi59@8(o21u-8x%s%vmh4#tc')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    'localhost',
    '127.0.0.1',
    'testserver',  # For running tests
    '16.79.83.21',  # EC2 server IP
    'lmsetjendpdri.duckdns.org',  # Production domain
    '.onrender.com',
    '.railway.app',
    '.vercel.app'
])

# Frontend and Backend URLs (for emails, redirects, etc.)
FRONTEND_SITE_URL = env('FRONTEND_SITE_URL', default='https://lmsetjendpdri.duckdns.org')
BACKEND_SITE_URL = env('BACKEND_SITE_URL', default='https://lmsetjendpdri.duckdns.org')

# ===========================
# Google OAuth Configuration (PHASE 4.16)
# ===========================
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default='')
GOOGLE_OAUTH_REDIRECT_URI = env('GOOGLE_OAUTH_REDIRECT_URI', default='http://localhost:5174/login')


# Application definition

INSTALLED_APPS = [
    'jazzmin', 

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Apps
    'core',
    'userauths',
    'api',

    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'anymail',
    'drf_yasg'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Compress response content for faster transfer
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database Configuration
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import urllib.parse

# Support for DATABASE_URL environment variable (prioritized over individual settings)
_database_url = env('DATABASE_URL', default=None)

print(f"DEBUG: DATABASE_URL value: {_database_url}")

if _database_url:
    print("DEBUG: Using DATABASE_URL configuration")
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
        )
    }
    print(f"DEBUG: DATABASES config: {DATABASES}")
else:
    print("DEBUG: Using individual DB configuration")
    # Fall back to individual configuration with URL-encoded password
    _DB_NAME = env('DB_NAME', default='secure_password')
    # URL-encode the password to handle special characters
    _DB_NAME_encoded = urllib.parse.quote(_DB_NAME, safe='')
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME', default='lms_db'),
            'USER': env('DB_USER', default='lms_user'),
            'PASSWORD': env('DB_PASSWORD', default='secure_password'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 600,  # 10 minutes connection persistence
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTH_USER_MODEL = 'userauths.User'

FRONTEND_SITE_URL = env("FRONTEND_SITE_URL", default="https://frontend-mtmk2t9bk-khazs-projects.vercel.app")


FROM_EMAIL = env("FROM_EMAIL", default="sdm@dpd.go.id")

# Use console email backend for development, SendGrid for production
SENDGRID_API_KEY = env("SENDGRID_API_KEY", default="")

if SENDGRID_API_KEY:
    ANYMAIL = {
        "SENDGRID_API_KEY": SENDGRID_API_KEY,
    }
    EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'
else:
    # Fallback to console backend if SendGrid is not configured
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:
#     ANYMAIL = {
#         "SENDGRID_API_KEY": env("SENDGRID_API_KEY"),
#     }
#     EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS  = {
    "site_title": "Desphixs LMS Admin",
    "site_header": "Desphixs LMS",
    "site_brand": "Desphixs LMS",
    # "site_logo": "path-to-logo",
    "welcome_sign": "Welcome to the Desphixs LMS",
    "copyright": "Desphixs LMS Ltd",
    "show_ui_builder": True,

}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-danger",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Optional
        'rest_framework_simplejwt.authentication.JWTAuthentication',        
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Default page size
    'DEFAULT_FILTER_BACKENDS': ['rest_framework.filters.SearchFilter', 'rest_framework.filters.OrderingFilter'],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',

    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# CORS Configuration for Frontend Integration
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://16.79.83.21",  # EC2 server IP (HTTP)
    "https://16.79.83.21",  # EC2 server IP (HTTPS)
    "https://lmsetjendpdri.duckdns.org",  # Production domain (HTTPS)
    "https://frontend-mtmk2t9bk-khazs-projects.vercel.app",  # Old production frontend
    "https://frontend-srfucwb9o-khazs-projects.vercel.app",  # New production frontend
    "https://frontend-p26ir11fd-khazs-projects.vercel.app",  # Alternative production frontend
])

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
    'authorization',
]

# Cache Configuration - Redis for production, local memory for development
try:
    # Try to use Redis if available
    import redis
    redis_client = redis.Redis.from_url(env('REDIS_URL', default='redis://localhost:6381/1'))
    redis_client.ping()
    
    # Redis is available, use Redis caching
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': env('REDIS_URL', default='redis://localhost:6381/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            },
            'KEY_PREFIX': 'lms',
            'TIMEOUT': 300,  # 5 minutes default timeout
        },
        # Separate cache for sessions
        'sessions': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': env('REDIS_URL', default='redis://localhost:6381/2'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'lms_session',
            'TIMEOUT': 86400,  # 24 hours for sessions
        },
        # Cache for course data and heavy queries
        'course_cache': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': env('REDIS_URL', default='redis://localhost:6381/3'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'lms_course',
            'TIMEOUT': 3600,  # 1 hour for course data
        }
    }
    # Use Redis for session storage
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'sessions'
    print("Using Redis for caching and sessions")
    
except Exception as e:
    # Redis not available, fallback to local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'lms-cache',
            'TIMEOUT': 300,
        },
        'sessions': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'lms-sessions',
            'TIMEOUT': 86400,
        },
        'course_cache': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'lms-course-cache',
            'TIMEOUT': 3600,
        }
    }
    # Use database sessions as fallback
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
    print("Redis not available, using local memory cache and database sessions")
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = False

# Database Query Optimization
DATABASE_QUERY_CACHE_TIMEOUT = 300  # 5 minutes for query results
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = 'lms_page'

# Performance Monitoring and Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'performance': {
            'format': '[PERF] {asctime} {name} {levelname}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            # Using FileHandler instead of RotatingFileHandler to avoid Windows file locking issues
            # You can manually rotate logs or use external log rotation tools
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'db_queries': {
            # Using FileHandler instead of RotatingFileHandler to avoid Windows file locking issues
            # You can manually rotate logs or use external log rotation tools
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'db_queries.log'),
            'formatter': 'performance',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['db_queries'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# Django Extensions for better development and monitoring
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar', 'django_extensions']
    # Insert debug_toolbar after GZipMiddleware to avoid middleware ordering warning
    gzip_index = MIDDLEWARE.index('django.middleware.gzip.GZipMiddleware')
    MIDDLEWARE.insert(gzip_index + 1, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    
    # Debug toolbar configuration
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
        'SHOW_TEMPLATE_CONTEXT': True,
    }
    
    INTERNAL_IPS = ['127.0.0.1', 'localhost']

# Enhanced Local File Storage Configuration
# Increased to 500MB to support large video uploads (matches MAX_VIDEO_FILE_SIZE)
FILE_UPLOAD_MAX_MEMORY_SIZE = env.int('FILE_UPLOAD_MAX_MEMORY_SIZE', default=524288001)  # 500MB
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int('DATA_UPLOAD_MAX_MEMORY_SIZE', default=524288001)  # 500MB
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'temp_uploads')
os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

# Organized Media Storage Structure
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Create organized media subdirectories
MEDIA_SUBDIRS = {
    'courses': os.path.join(MEDIA_ROOT, 'courses'),
    'profiles': os.path.join(MEDIA_ROOT, 'profiles'),
    'certificates': os.path.join(MEDIA_ROOT, 'certificates'),
    'thumbnails': os.path.join(MEDIA_ROOT, 'thumbnails'),
    'documents': os.path.join(MEDIA_ROOT, 'documents'),
    'videos': os.path.join(MEDIA_ROOT, 'videos'),
    'images': os.path.join(MEDIA_ROOT, 'images'),
    'backups': os.path.join(BASE_DIR, 'backups', 'media')
}

# Create directories if they don't exist
for dir_path in MEDIA_SUBDIRS.values():
    os.makedirs(dir_path, exist_ok=True)

# File Size Limits by Type
MAX_FILE_SIZES = {
    'video': env.int('MAX_VIDEO_FILE_SIZE', default=524288001),    # 500MB
    'image': env.int('MAX_IMAGE_FILE_SIZE', default=52428800),     # 50MB
    'document': env.int('MAX_DOCUMENT_FILE_SIZE', default=104857600), # 100MB
    'audio': env.int('MAX_AUDIO_FILE_SIZE', default=104857600),    # 100MB
}

# Local Storage Optimization Settings
USE_LOCAL_OPTIMIZATION = env.bool('USE_LOCAL_OPTIMIZATION', default=True)
ENABLE_FILE_COMPRESSION = env.bool('ENABLE_FILE_COMPRESSION', default=True)
ENABLE_IMAGE_OPTIMIZATION = env.bool('ENABLE_IMAGE_OPTIMIZATION', default=True)
STORE_THUMBNAILS_IN_DB = env.bool('STORE_THUMBNAILS_IN_DB', default=True)
MEDIA_CACHE_DURATION = env.int('MEDIA_CACHE_DURATION', default=3600)

# Security Enhancements for Production
if not DEBUG:
    # SSL/HTTPS settings (optional - set USE_SSL=True when you have SSL certificate)
    USE_SSL = env.bool('USE_SSL', default=False)
    
    if USE_SSL:
        SECURE_SSL_REDIRECT = True
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
    
    # Always enable these security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True

# CRITICAL: Proxy SSL Header Configuration
# This tells Django to trust the X-Forwarded-Proto header from nginx
# Without this, build_absolute_uri() generates HTTP URLs even when accessed via HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Trust X-Forwarded-Host header from nginx
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# ============================================================================
# AUTORELOADER CONFIGURATION FOR WINDOWS
# ============================================================================
# Fix for autoreloader not properly inheriting venv on Windows
# When DEBUG=True, Django's autoreloader spawns a subprocess which was losing
# the venv's sys.path and environment variables
# See: https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-runserver
import sys
if DEBUG and sys.platform == 'win32':
    # Use WatchmanReloaderClass or PollingReloader if autoreloader fails
    # This ensures subprocess properly inherits sys.executable and venv
    os.environ['RUN_MAIN'] = 'true'