# Generated by Django 4.2.7 on 2025-09-30 15:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('external_id', models.CharField(blank=True, help_text='External system user ID', max_length=50, null=True, unique=True)),
                ('nip', models.CharField(blank=True, help_text='Employee ID number', max_length=50, null=True)),
                ('golongan', models.CharField(blank=True, help_text='Employee grade/rank', max_length=20, null=True)),
                ('kelas_jabatan', models.CharField(blank=True, help_text='Position class', max_length=50, null=True)),
                ('jenis_jabatan', models.CharField(blank=True, help_text='Position type', max_length=50, null=True)),
                ('timezone', models.CharField(default='Asia/Jakarta', help_text='User timezone', max_length=50)),
                ('external_status', models.CharField(default='ACTIVE', help_text='External system status', max_length=20)),
                ('external_created_at', models.DateTimeField(blank=True, help_text='External system creation date', null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, help_text='External system update date', null=True)),
                ('last_sync_date', models.DateTimeField(blank=True, help_text='Last synchronization with external system', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='External system unit ID', unique=True)),
                ('name', models.CharField(help_text='Organization unit name', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'verbose_name_plural': 'Organization Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='External system position ID', unique=True)),
                ('name', models.CharField(help_text='Position name', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default-user.jpg', null=True, upload_to='user_folder')),
                ('full_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bio', models.CharField(blank=True, help_text='Short bio', max_length=500, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('organization_unit', models.ForeignKey(blank=True, help_text="User's organization unit", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.organizationunit')),
                ('position', models.ForeignKey(blank=True, help_text="User's position/job", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default-user.jpg', null=True, upload_to='admin_folder')),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('permissions', models.TextField(blank=True, help_text='JSON field for admin permissions', null=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
