# Generated by Django 4.2.7 on 2025-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='admin_folder'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_folder'),
        ),
    ]
