# Generated by Django 4.2.7 on 2026-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_user_options_user_userauths_u_role_7b2cef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', help_text='Currently active role for this session', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(default='student', help_text='Comma-separated roles: student,teacher,admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', help_text='DEPRECATED: Use roles field instead', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['current_role'], name='userauths_u_current_da43e1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['current_role', 'is_active'], name='userauths_u_current_b05c08_idx'),
        ),
    ]
