# Generated by Django 4.2.8 on 2026-02-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0006_add_boolean_role_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="userauths_u_is_stu_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="userauths_u_is_ins_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="userauths_u_is_adm_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="userauths_u_is_stu_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="userauths_u_is_ins_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="userauths_u_is_adm_active_idx",
        ),
        migrations.AlterField(
            model_name="organizationunit",
            name="external_id",
            field=models.CharField(
                help_text="External system unit ID", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="external_id",
            field=models.CharField(
                help_text="External system position ID", max_length=50, unique=True
            ),
        ),
    ]
