# Generated by Django 4.2.8 on 2026-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0007_remove_user_userauths_u_is_stu_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
