# Generated by Django 4.2.8 on 2026-05-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0009_alter_profile_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_student"], name="userauths_u_is_stud_767e01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_instructor"], name="userauths_u_is_inst_9d0c1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_admin"], name="userauths_u_is_admi_a23204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["external_id"], name="userauths_u_externa_40b8ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["external_status"], name="userauths_u_externa_1df221_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_student"],
                name="userauths_u_is_acti_d2193b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_instructor"],
                name="userauths_u_is_acti_e9422e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_admin"], name="userauths_u_is_acti_fb6506_idx"
            ),
        ),
    ]
