# Generated by Django 4.2.7 on 2026-09-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0010_user_userauths_u_is_stud_767e01_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsedSSOToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_signature",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Used SSO Token",
                "db_table": "used_sso_tokens",
            },
        ),
    ]
