# Generated by Django 4.2.7 on 2026-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0011_usedssotoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_internal",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is an internal DPD RI employee.",
            ),
        ),
    ]
